-- MySQL Script generated by MySQL Workbench
-- Mon Oct 18 23:50:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `Customer_SK` INT NOT NULL,
  `Customer_Name` VARCHAR(45) NULL,
  `Customer_Country` VARCHAR(45) NULL,
  `Customer_State` VARCHAR(45) NULL,
  `Customer_City` VARCHAR(45) NULL,
  `Customer_ZipCode` VARCHAR(45) NULL,
  `Customer_StreetAddress1` VARCHAR(45) NULL,
  `Customer_StreetAddress2` VARCHAR(45) NULL,
  PRIMARY KEY (`Customer_SK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Options` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Options` (
  `Options_SK` INT NOT NULL,
  `OrderMethod` VARCHAR(45) NULL,
  `PaymentMethod` VARCHAR(45) NULL,
  `ShippingOpt` VARCHAR(45) NULL,
  PRIMARY KEY (`Options_SK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `Order_SK` INT NOT NULL,
  `Order_Year` INT NULL,
  `Order_Qtr` INT NULL,
  `Order_Week` VARCHAR(20) NULL,
  `Order_Month` VARCHAR(20) NULL,
  `Order_Day` VARCHAR(45) NULL,
  `Order_Date` DATE NULL,
  `OrderFicsal_Year` INT NULL,
  `OrderFiscal_Qtr` INT NULL,
  `OrderFiscal_Month` VARCHAR(45) NULL,
  `OrderFiscal_Week` VARCHAR(45) NULL,
  PRIMARY KEY (`Order_SK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `Product_SK` INT NOT NULL,
  `Business_Unit` INT NULL,
  `Product_Type` VARCHAR(45) NULL,
  `Product_Name` VARCHAR(45) NULL,
  `Price1` INT NULL,
  `Price2` INT NULL,
  `Product_Desc` VARCHAR(45) NULL,
  `UnitCost` INT NULL,
  `BAbbr` VARCHAR(45) NULL,
  PRIMARY KEY (`Product_SK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sales_Date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sales_Date` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sales_Date` (
  `Sales_Date_SK` INT NOT NULL,
  `Sales_Year` INT(4) NULL,
  `Sales_Qtr` INT NULL,
  `Sales_Month` VARCHAR(45) NULL,
  `Sales_Week` VARCHAR(45) NULL,
  `Sales_Day` VARCHAR(45) NULL,
  `Sales_Date` DATE NULL,
  `SalesDate_Fiscal_Year` INT NULL,
  `SalesDate_Fiscal_Qtr` INT NULL,
  `SalesDate_Fiscal_Month` VARCHAR(45) NULL,
  `SalesDate_Fiscal_Week` VARCHAR(45) NULL,
  PRIMARY KEY (`Sales_Date_SK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sales_Fact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sales_Fact` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sales_Fact` (
  `Customer_SK` INT NOT NULL,
  `Product_SK` INT NOT NULL,
  `Payment_SK` INT NOT NULL,
  `Shipping_SK` INT NOT NULL,
  `Supplier_SK` INT NOT NULL,
  `Sales_Date_SK` INT NOT NULL,
  `Order_SK` INT NOT NULL,
  `Invoiceno` VARCHAR(12) NULL,
  `ManfCost` INT NULL,
  `Total` INT NULL,
  `Quantity` INT NULL,
  `GrossProfit` INT NULL,
  `Fullfilldays` INT NULL,
  `Shipdays` INT NULL,
  INDEX `Customer_SK_idx` (`Customer_SK` ASC) VISIBLE,
  INDEX `Product_SK_idx` (`Product_SK` ASC) VISIBLE,
  INDEX `Shipping_SK_idx` (`Shipping_SK` ASC) VISIBLE,
  INDEX `Order_SK_idx` (`Order_SK` ASC) VISIBLE,
  INDEX `Supplier_SK_idx` (`Supplier_SK` ASC) VISIBLE,
  INDEX `Sales_Date_SK_idx` (`Sales_Date_SK` ASC) VISIBLE,
  INDEX `Options_SK_idx` (`Payment_SK` ASC) VISIBLE,
  PRIMARY KEY (`Shipping_SK`, `Payment_SK`, `Sales_Date_SK`, `Product_SK`, `Order_SK`, `Customer_SK`, `Supplier_SK`),
  CONSTRAINT `Customer_SK`
    FOREIGN KEY (`Customer_SK`)
    REFERENCES `mydb`.`Customer` (`Customer_SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Product_SK`
    FOREIGN KEY (`Product_SK`)
    REFERENCES `mydb`.`Product` (`Product_SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Shipping_SK`
    FOREIGN KEY (`Shipping_SK`)
    REFERENCES `mydb`.`Shipping` (`Shipping_SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Order_SK`
    FOREIGN KEY (`Order_SK`)
    REFERENCES `mydb`.`Order` (`Order_SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Supplier_SK`
    FOREIGN KEY (`Supplier_SK`)
    REFERENCES `mydb`.`Supplier` (`Supplier_SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Sales_Date_SK`
    FOREIGN KEY (`Sales_Date_SK`)
    REFERENCES `mydb`.`Sales_Date` (`Sales_Date_SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Options_SK`
    FOREIGN KEY (`Payment_SK`)
    REFERENCES `mydb`.`Options` (`Options_SK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shipping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Shipping` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Shipping` (
  `Shipping_SK` INT NOT NULL,
  `Shipping_Year` INT(4) NULL,
  `Shipping_Qtr` INT NULL,
  `Shipping_Month` VARCHAR(45) NULL,
  `Shipping_Week` VARCHAR(45) NULL,
  `Fiscal_Month` VARCHAR(45) NULL,
  `Fiscal_Week` VARCHAR(45) NULL,
  `Fiscal_Year` INT NULL,
  `Fiscal_Qtr` INT NULL,
  `Shipping_Day` VARCHAR(45) NULL,
  `Shipping_Date` DATE NULL,
  PRIMARY KEY (`Shipping_SK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Supplier` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `Supplier_SK` INT NOT NULL,
  `Supplier_Name` VARCHAR(45) NULL,
  `Supplier_Country` VARCHAR(45) NULL,
  `Supplier_State` VARCHAR(45) NULL,
  `Supplier_City` VARCHAR(45) NULL,
  `Supplier_Zip` VARCHAR(10) NULL,
  `SupplierStreetAddr` VARCHAR(45) NULL,
  PRIMARY KEY (`Supplier_SK`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
